# Generated by Django 4.2.4 on 2023-11-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv", name="pdf", field=models.FileField(upload_to="mycv/"),
        ),
    ]
