# Generated by Django 4.2.4 on 2023-12-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_alter_cv_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
