# Generated by Django 5.0.2 on 2024-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_about_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
